"""empty message

Revision ID: 4546275f6919
Revises: 
Create Date: 2023-04-24 10:32:20.196309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4546275f6919'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=220), nullable=True),
    sa.Column('photo_filename', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_user_email')),
    sa.UniqueConstraint('username', name=op.f('uq_user_user_username'))
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=50), nullable=False),
    sa.Column('date_writing', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=220), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('pdf_filename', sa.String(length=100), nullable=True),
    sa.Column('image_filename', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_book_book_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book'))
    )
    op.create_table('text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_text_text_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_text'))
    )
    op.create_table('book_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('fk_book_rating_book_rating_book_id_book')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_book_rating_book_rating_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_book_rating'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_rating')
    op.drop_table('text')
    op.drop_table('book')
    op.drop_table('user')
    # ### end Alembic commands ###
